// <auto-generated />
using System;
using InsurancePolicy.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InsurancePolicy.Infrastructure.Data.Migrations
{
    [DbContext(typeof(InsurancePolicyDbContext))]
    [Migration("20200801193047_MigrationInsurancePolicy-v1")]
    partial class MigrationInsurancePolicyv1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InsurancePolicy.Domain.Models.CoverageType", b =>
                {
                    b.Property<int>("CoverageTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoverageTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverageTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CoverageTypeID");

                    b.ToTable("CoverageTypes");
                });

            modelBuilder.Entity("InsurancePolicy.Domain.Models.InsurancePolicy", b =>
                {
                    b.Property<int>("InsurancePolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CoveragePercentage")
                        .HasColumnType("int");

                    b.Property<int>("CoverageTimeElapsed")
                        .HasColumnType("int");

                    b.Property<int>("CoverageTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiskTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Startdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusTypeID")
                        .HasColumnType("int");

                    b.Property<float>("TotalCost")
                        .HasColumnType("real");

                    b.HasKey("InsurancePolicyID");

                    b.ToTable("InsurancePolicies");
                });

            modelBuilder.Entity("InsurancePolicy.Domain.Models.RiskType", b =>
                {
                    b.Property<int>("RiskTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxCoverage")
                        .HasColumnType("int");

                    b.Property<string>("RiskTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RiskTypeID");

                    b.ToTable("RiskTypes");
                });

            modelBuilder.Entity("InsurancePolicy.Domain.Models.StatusType", b =>
                {
                    b.Property<int>("StatusTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StatusTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusTypeID");

                    b.ToTable("StatusTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
